### ISSUE TITLE
bug: Tattoo not workin' properly

### ISSUE THREAD

**Issue by tokitou-san** [baseplate-admin/new_blog#10]
![Screenshot from 2023-09-01 16-21-08](https://github.com/baseplate-admin/new_blog/assets/114811070/611a4870-03a1-4a71-9992-1ea16a387e61)

Change this active thingy when its related section comes at least 25 - 40%.
Current behaviour: it changes even when its related section is not in the view.
Tattooing not correct :\

**Comment by baseplate-admin** [comment]
Fixed :D
